### ISSUE TITLE
PYROSCOPE_PROFILER_EVENT always itimer

### ISSUE THREAD

**Issue by netamego** [pyroscope-io/pyroscope-java#1]
Wooow this is an amazing project and java profiling is a must. I think there isn't best approach than async-profiler to do it. Congratulations!!!

I have tested the java agent and looks very promising. The only mistake I have found is that seems always use itimer profiler. No wall or alloc profiler. I have tested with Jenkins java app and the flame graph is exactly the same when i set PYROSCOPE_PROFILER_EVENT to wall, itimer or alloc. Maybe I am doing something wrong.

Would be incredible support for wall profiling at least. It's a great profiling method to detect latency issues.

Last but not least, as a suggestion, would be great the Flamegraph Title change accoring profiler (wall, itimer, alloc, etc)

![image](https://user-images.githubusercontent.com/10206580/137603828-d61628bb-139c-4164-9794-a5c3e4b80ccf.png)

I see a very promising future for Pyroscope. 

Keep going!!

Best regards.

**Comment by ivanyu** [comment]
Hi @netamego 
Thanks for reporting this. It seems really we always use `ITIMER`:

https://github.com/pyroscope-io/pyroscope-java/blob/main/agent/src/a9c39e345f3129f96b6b40631b17d2cf15bef9a2/java/io/pyroscope/javaagent/PyroscopeAgent.java#L43

Needs fixing

**Comment by Rperry2174** [comment]
Hey @netamego should be working now! Let us know if you have any issues or other feedback
