### ISSUE TITLE
Java 7 support for Pyroscope Java Agent

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope-java#10]
Copying from Pyroscope [main repo](https://github.com/pyroscope-io/pyroscope/issues/747):

> Hi,
> 
> Pyroscope is amazing!!! I use it in java 1.8 apps without problems and the use of asyc-profiler was the best aproach that could be taken.
> 
> My problem is that I have a lot of apps in Java 1.7 and I can't compile Pyroscope Java Agent for Java 1.7 version because two files in source code use "lambda expressions" and "method references" that are not supported in Java 1.7
> 
> Could be possible to make Java Agent source code compatible with java 1.7?

**Comment by korniltsev** [comment]
We've built a separate artifact `io.pyroscope:agent-jdk7:0.9.1.1` for java 1.7 https://mvnrepository.com/artifact/io.pyroscope/agent-jdk7

We have no plans merging it to main branch.

**Comment by netamego** [comment]
Thank you very much @korniltsev. Great Pyroscope Team. Listening to the comunity.

Thanks.
