### ISSUE TITLE
Implement support for dynamic tags

### ISSUE THREAD

**Issue by petethepig** [pyroscope-io/pyroscope-java#14]
Other integrations have ways to set tags dynamically from the profiled application.

We'd love to be able to support dynamic tags in java for two main use cases:

## Use case 1: Supporting Dynamic tags for user-defined scopes
Often users want to tag a region, namespace, pod, container, machine, etc and dynamic tags would allow them to do this.
e.g here's how it's done in go: https://github.com/pyroscope-io/pyroscope/blob/main/examples/golang-push/rideshare/utility/utility.go#L46-L57

And we then support using these tags to compare and calculate diffs between profiles. I.e. here we are showing the diff between the `region` tags:
- `ride-sharing-app.cpu{region="us-west-1"}`
- `ride-sharing-app.cpu{region="eu-west-1"}`

### Comparing two tags
<img width="1790" alt="Screen Shot 2022-04-06 at 5 40 17 PM" src="https://user-images.githubusercontent.com/23323466/162076438-c5936706-1c15-4935-b457-a6509ea57be3.png">

### Diff between two tags
See [here](https://flamegraph.com/share/82523d01-b5f2-11ec-99c9-46d6c6aefeb9) for interactive example
![image](https://user-images.githubusercontent.com/23323466/162076875-62a4b5b4-c280-4e57-8751-734975cd33a6.png)

## Use case 2: Supporting `profile_id` tag for profiling exemplars
We recently created a [otelpyroscope](https://github.com/pyroscope-io/otelpyroscope) package which is meant to link trace spans from a distributed tracing system (i.e. jaeger) to profiles

How this works is:
- when a span is created, we begin profiling in that thread and tag that profile with a corresponding `profile_id`
- the pyroscope agent then sends that profile to the server where it is stored in an exemplar-specific db (separate from other profiling data)
- If the `profile_id` tag value is stored in metadata people can then retrieve this via tracing UI's 

i.e. in this image you can embed a profile for this particular span, because it was conveniently tagged as 
`pyroscope.profile.id = 840f2c4bd6e4a2c4`

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/23323466/162067415-07737db7-9978-4f2b-a99a-bc9b7a0faa66.png">

Reference:
OTEL issue about standardizing profile formats: https://github.com/open-telemetry/oteps/issues/139
Async-profiler PR attempting to add (a type) of tag: https://github.com/jvm-profiling-tools/async-profiler/pull/576

**Comment by netamego** [comment]
Hi!! 

Could be posible use labels/tags and app aggregation without modofing the source code of my app. I don't know if is feadible but would be great se could define tags/labels with an exported variable. 

Thanks.

**Comment by Rperry2174** [comment]
Hi @netamego I'm going to go ahead and close this issue since this one is complete. 
- [Docs](https://pyroscope.io/docs/java/#labels)
- [Examples](https://github.com/pyroscope-io/pyroscope/blob/main/examples/java-jfr/rideshare/README.md)

If you dont mind could you create a separate issue around using labels/tags in the way that you'd like (with an example of the use case)?
