### ISSUE TITLE
Exponential backoff in push mode appears to just back off forever

### ISSUE THREAD

**Issue by lizthegrey** [pyroscope-io/pyroscope-java#15]
After the backend goes down, or if the backend wasn't up during process startup, no further telemetry is sent from pyroscope java agent. whole process has to be bounced for telemetry to resume.

**Comment by ivanyu** [comment]
Hi @lizthegrey 
Is there anything in the logs?

**Comment by lizthegrey** [comment]
> Hi @lizthegrey Is there anything in the logs?

no, because I don't have debug mode enabled on the agent. no instances of any of the strings in https://github.com/pyroscope-io/pyroscope-java/blob/main/agent/src/main/java/io/pyroscope/javaagent/Uploader.java in the kafka server logs.

**Comment by lizthegrey** [comment]
Oh wait, journalctl has it. one moment.

```
```

**Comment by lizthegrey** [comment]
@ivanyu looks like `ExponentialBackoff.java:27` passes a negative number to `Random.nextInt()` somehow, maybe overflow of some kind?
