### ISSUE TITLE
macos-aarch64 support

### ISSUE THREAD

**Issue by tokuhirom** [pyroscope-io/pyroscope-java#24]
I want to run pyroscope-java on M1 Mac.

async-profiler 2.5+ supports macos-aarch64.
https://github.com/jvm-profiling-tools/async-profiler/issues/390

**Comment by petethepig** [comment]
Looks like we'd need to
* update async profiler version
* update the code [here](https://github.com/pyroscope-io/pyroscope-java/blob/c0dd817b628d9f9d83fcc94972b405d0562ca9c6/agent/src/main/java/io/pyroscope/javaagent/Profiler.java#L88-L94)

**Comment by abeaumont** [comment]
Provided by #29
