### ISSUE TITLE
Support configuration using system properties

### ISSUE THREAD

**Issue by pvid** [pyroscope-io/pyroscope-java#32]
It is more convenient to use system properties for configuration.

OpenTelemetry for example allows to use both properties and env variables for configuration, with properties taking precedence, see [their implementation](https://github.com/open-telemetry/opentelemetry-java/blob/7b6a7c9a3f7ccc88a7c468e9ce5103e1a6918b33/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/DefaultConfigProperties.java).

**Comment by netamego** [comment]
+1000 :)

I totally agree. It is a very necessary option especially when you profile WebLogic application servers where it is difficult to use environment variables for each java process. It is a headache to use environment variables to configure pyroscope in WebLogic environments. https://stackoverflow.com/questions/23620163/best-way-to-set-environmental-variables-in-weblogic-startup

Thanks a lot @abeaumont . You are doing fast and amazing work.

**Comment by korniltsev** [comment]
We've implemented configuration with properties in v0.9.0.
You can now specify pyroscope configuration:
- from system properties `-Dpyroscope.format=jfr` 
- from `pyroscope.properties` file/resource `pyroscope.format=jfr`. 

Also `pyroscope.properties` can be changed to arbitrary location with `PYROSCOPE_CONFIGURATION_FILE` or `pyroscope.configuration` property
