### ISSUE TITLE
The agent is preventing the app from finishing.

### ISSUE THREAD

**Issue by abeaumont** [pyroscope-io/pyroscope-java#6]
The agent should detect when the main app finishes and then finish too. While this may be usually fine for continuous profiling, it can be problematic for adhoc mode.

**Comment by ivanyu** [comment]
Oops, I think it's this executor:
https://github.com/pyroscope-io/pyroscope-java/blob/451681ebe2e30fb6318b70d4410ec4320161e0f5/agent/src/main/java/io/pyroscope/javaagent/PyroscopeAgent.java#L45

It either needs using a thread factory that produces daemon threads or indeed shut it down explicitly when the app exits.
