### ISSUE TITLE
Add tags through setting environment of variables

### ISSUE THREAD

**Issue by nthnb** [pyroscope-io/pyroscope-java#60]
Hi, a feature request that would be really helpful for us would be to be able to add tags to our samples via setting of environment variables for the agent. For instance, if we set:
PYROSCOPE_PROFILER_TAG_XXX=yyy

This could be converted to:
Pyroscope.setStaticLabels(Map.of("xxx", System.getenv("PYROSCOPE_PROFILER_TAG_XXX")));

This would be variable helpful if we wanted to filter by say, deployment version of our apps. Please let me know you need any more information! Thanks

**Comment by Rperry2174** [comment]
Hi @nthnb we just added this recently in #57. 

You can find docs for it [here](https://pyroscope.io/docs/java/#:~:text=PYROSCOPE_LABELS%20sets%20static%20labels%20in%20the%20form%20of%20comma%20separated%20key%3Dvalue%20pairs.%20The%20default%20value%20is%20%22%22%20%2D%20enpty%20string%2C%20no%20labels.)

Let us know if we can improve the docs or feature in any way!

**Comment by nthnb** [comment]
Perfect! I missed that when looking through the docs, that's my bad. Thanks for the help! I'll close this issue now

**Comment by Rperry2174** [comment]
no worries @nthnb please let us know if you have any other feedback / requests!
