### ISSUE TITLE
Consider Replacing log4j with another logger

### ISSUE THREAD

**Issue by Rperry2174** [pyroscope-io/pyroscope-java#7]
We don't use logging that extensively in our agent, but due to recent events it seems as though it may be worthwhile to just switch from log4j to use another logger. Would be open to any other suitable logger here.

**Comment by ivanyu** [comment]
Considering the amount of attention of security researchers log4j has been enjoying recently, it probably can be considered quite secure now :)

**Comment by Rperry2174** [comment]
@ivanyu fair enough... We'll consider them on strike two. One more and I think we will have to _strongly_ consider the switch :)
