### ISSUE TITLE
Dynamic labels not working 

### ISSUE THREAD

**Issue by valodzka** [pyroscope-io/pyroscope-java#93]
As of agent 0.11.3, this code adds label region=test but now unit=test:

```
    public static void main(String[] args) {
        Pyroscope.setStaticLabels(Map.of("region", "test"));

        for (int i = 0; i < 2; ++i) {
            Pyroscope.LabelsWrapper.run(new LabelsSet(Map.of("unit", "test")), () -> {
                try {
                    Thread.sleep(5_000);
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }
            });
        }
    }
```

![image](https://user-images.githubusercontent.com/9821/234004474-097b26ac-5b60-4623-a3d5-0295e5247802.png)

**Comment by korniltsev** [comment]
Can you try replacing Thread.sleep with something burning cpu?
What is your configuration?

**Comment by korniltsev** [comment]
by default it uses collapsed format, labels are supported only with JFR format

**Comment by valodzka** [comment]
yes, can confirm, with JFR it's working
